version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: cazico-db
    environment:
      MYSQL_DATABASE: cazico
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  management-app:
    build: infra/management-console/php
    depends_on:
      - mysql
      - redis
    volumes:
      - ./src/management-console:/var/www/html/management-console
  management-web:
    build: infra/management-console/nginx
    depends_on:
      - management-app
    image: nginx:1.20-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/management-console:/var/www/html/management-console
      - ./infra/management-console/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
