version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: cazico-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cazico
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
