version: "3.9"

services:
  db:
    image: mysql/mysql-server:8.0
    command: --secure-file-priv=""
    environment:
      MYSQL_DATABASE: cazico
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql

  management-app:
    build: infra/management-console/php
    depends_on:
      - db
      - redis
    volumes:
      - ./src/management-console:/var/www/html/management-console

  management-web:
    depends_on:
      - management-app
    image: nginx:1.20-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/management-console:/var/www/html/management-console
      - ./infra/management-console/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

volumes:
  db-store:
